### ISSUE TITLE
request dependancy missing

### ISSUE THREAD

**Issue by larkov** [vinaywadhwa/justwatch-alfred#1]
Getting this error in Alfred as some dependancy is missing on my machine.

`[17:11:44.368] Logging Started...
[17:11:46.700] Just Watch (Unofficial)[Script Filter] Queuing argument 'fr'
[17:11:46.817] Just Watch (Unofficial)[Script Filter] Script with argv '(null)' finished
[17:11:46.820] ERROR: Just Watch (Unofficial)[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from lib.justwatch import JustWatch
  File "/Users/lari/Dropbox/AlfredApp/Alfred.alfredpreferences/workflows/user.workflow.75D5FD04-C1A0-4EE1-ACAC-EF1030704443/lib/justwatch/__init__.py", line 1, in <module>
    from .justwatchapi import JustWatch
  File "/Users/lari/Dropbox/AlfredApp/Alfred.alfredpreferences/workflows/user.workflow.75D5FD04-C1A0-4EE1-ACAC-EF1030704443/lib/justwatch/justwatchapi.py", line 3, in <module>
    import requests
ImportError: No module named requests`

**Comment by vinaywadhwa** [comment]
I tried fixing it. Can you try the latest version (1.0.1) from here? https://github.com/vinaywadhwa/justwatch-alfred/releases

**Comment by larkov** [comment]
Yes, works fine with the new release.
